platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!
  #pod 'composeApp', :path => '../composeApp'
  #pod 'AppMetricaCore', '5.11.1'
  #pod 'AppMetricaPush', '3.1.0'
  #pod 'AppMetricaPushLazy', '3.1.0'
  pod 'FirebaseCore', '11.14.0'
  pod 'FirebaseAnalytics', '11.14.0'
  pod 'FirebaseCrashlytics', '11.14.0'
  pod 'FirebaseMessaging', '11.14.0'
  pod 'PurchasesHybridCommon', '13.36.0'
  pod 'FBSDKCoreKit', '18.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ASSETCATALOG_COMPILER_APPICON_NAME'] = ''
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end